const { cmd } = require('../command');
const axios = require('axios');

const BOTNAME = "『𝙒𝘼・𝙃𝙄𝙎・𝙑𝟭』";

cmd({
  pattern: "img",
  alias: ["image", "pinterest", "pinimg"],
  react: '🖼️',
  desc: "Search and download images from Pinterest using keywords.",
  category: "image",
  use: ".img <keywords>",
  filename: __filename
}, async (conn, message, context, { from, args, reply }) => {
  try {
    const searchQuery = args.join(" ");
    if (!searchQuery) return reply("🎭 *Please provide keywords to summon the images...*");
    
    reply(`🔎 *Searching the depths of the web for:* "${searchQuery}"...`);
    
    const apiUrl = 'https://rubenbot-subzero-api.hf.space/download/piniimg?text=' + encodeURIComponent(searchQuery);
    const response = await axios.get(apiUrl);
    
    if (!response.data || !response.data.result || response.data.result.length === 0) {
      return reply(`❌ *No images dared to show for:* "${searchQuery}". Try another spell.`);
    }
    
    const images = response.data.result;
    let sentAny = false;
    
    for (let i = 0; i < Math.min(images.length, 5); i++) {
      const img = images[i];
      if (img.images_url) {
        sentAny = true;
        await conn.sendMessage(from, {
          image: { url: img.images_url },
          caption: `🎭 *Image ${i + 1} from your search* 🎭\n\n*© Generated by ${BOTNAME}*`
        }, { quoted: message });
      }
    }
    
    if (!sentAny) {
      reply(`❌ *No valid image URLs found in the results.*`);
    }
    
  } catch (error) {
    console.error(error);
    reply("❌ *An error occurred while processing your request.*");
  }
});